added support for multiple parents
CircleCI-Public/cimg-shared pull request #57
Opened 2022-03-25 20:52 UTC by JalexChen

- added 3 new variables to manifest:
-- parentTags supports Elixir and Clojure, allowing them to choose versions of Erlang and OpenJDK, respectively
-- defaultParentTag tracks the default tag for new version updates
-- parentSlug helps to differentiate from diverging repository/parent names and to help track for Dockerfile builds

- Refactored parser to take in variables and account for all cases
- Added build and push function to help generate Docker strings

2022-03-28 18:43 UTC, felicianotech requested changes
I ran a test locally with the Go image. It most works but a few things. We're really close!

So for my test with cimg/go, I set the following in the manifest:

```
parentTags=(18.04 20.04)
defaultParentTag=20.04
parentSlug=ubuntu
```

In `Dockerfile.template`, I have this FROM line:

```
FROM cimg/%%PARENT%%:edge-%%PARENT_TAG%%
```

After running the generate script, I get a Dockerfile that doesn't quit have the correct FROM line. Here's what it looks like (first line) and here's what I would expect it to look like (second line).

```
FROM cimg/go:edge-1.18.1-ubuntu-20.04
FROM cimg/base:edge-ubuntu-20.04
```

Notice that the image name is `go` instead of `base` and that the version string `1.18.1` is there which shouldn't be there at all.

Lastly, a suggestion I have, which might be best to save for a separate PR after this one gets merged, is to support having the parent slug be empty. In that case, the slug would be nothing and the extra hyphen wouldn't be there either. Again, this can be after this PR though. I'll create a separate issue for that one.

2022-03-28 18:43 UTC, felicianotech commented on gen-dockerfiles.sh
> +# %%VERSIONING%% - repurposed from %%MAIN_VERSION%% to be used to specify a specific versioning scheme
This looks wrong. `MAIN_VERSION` is deprecated and already replaced by `VERSION_FULL`.

2022-03-28 18:43 UTC, felicianotech commented on gen-dockerfiles.sh
> +	# versioning is mainly used to parse specific Erlang versions
`cimg-shared` is the general tooling system for all Convenience Images. We shouldn't have image specifics here.

2022-03-28 18:43 UTC, felicianotech commented on gen-dockerfiles.sh
> +	local fileTemplate=${4}
I'm not following. Can you please explain how this works to me? Parent and parentTag looking familiar but the others don't and I'm trying to figure out why we set these here and like this.

Is this so that we can create that directory structure under the main version/tag for sibling images/Dockerfiles?

2022-03-28 18:43 UTC, felicianotech commented on gen-dockerfiles.sh
> +	sed -i.bak 's/%%VERSIONING%%/'"${versioning}"'/g' "./${versionShort}/${variantPath}Dockerfile"  # will be deprecated in the future
Same comment as about. Also, the deprecation comment is still here.

2022-03-28 18:43 UTC, felicianotech commented on gen-dockerfiles.sh
> +	sed -i.bak 's!%%ALIAS1%%!'"${vgAlias1}"'!g' "./${versionShort}/${variantPath}Dockerfile"
I assume these three lines here is to assist with better parsing? LGTM

2022-03-28 18:43 UTC, felicianotech commented on gen-dockerfiles.sh
> +	# for every parentTag, there will be an additional 3 Dockerfiles
Why three?

2022-03-29 17:22 UTC, JalexChen commented on gen-dockerfiles.sh
> +	local fileTemplate=${4}
That's correct. I'm passing in paths for directory creation and a path to the template file based on what needs to be created.

2022-03-29 17:25 UTC, JalexChen commented on gen-dockerfiles.sh
> +	sed -i.bak 's/%%VERSIONING%%/'"${versioning}"'/g' "./${versionShort}/${variantPath}Dockerfile"  # will be deprecated in the future
This should be fixed in the new update

2022-03-29 17:26 UTC, JalexChen commented on gen-dockerfiles.sh
> +	sed -i.bak 's!%%ALIAS1%%!'"${vgAlias1}"'!g' "./${versionShort}/${variantPath}Dockerfile"
%%MAIN_SHA%% is deprecated and should technically be removed from parsing (?)

2022-03-29 17:29 UTC, JalexChen commented on gen-dockerfiles.sh
> +	# for every parentTag, there will be an additional 3 Dockerfiles
The way I'm thinking about it is that every parentTag will generate two variants and a base Dockerfile in addition to the original three that are generated from the defaultParentTag

2022-03-30 16:11 UTC, felicianotech requested changes
From the example I gave from my last review, I ran it again and got this:

```
FROM cimg/base:edge-ubuntu20.04
```

So the `1.18.1` version was removed, which is great. But now we lost the hyphen between the `parentSlug` and `parentTag`.

I then ran a test with the Elixir image as we discussed on Zoom yesterday and I got this line:

```
 ENV ERLANG_VERSION="erlang23.0.0" 
```

So the problem here is, the parentSlug is being used for the `%%PARENT_TAG%%` template variable. That is incorrect. It just just be the tag/version itself.

2022-03-30 16:11 UTC, felicianotech commented on manifest
> +parentSlug=nothing
It doesn't hurt to add this but just keep in mind that none of this is needed. `cimg-shared` isn't an image repo so a manifest file isn't needed/used.

2022-03-30 16:16 UTC, felicianotech commented
Also, when parentTags are activated, we need to disable:

1. the creation of the Dockerfiles that are outside of parentTags
2. the building of those Dockerfiles in the build file
3. the pushing of those in the push file (although maybe this part is fine, since those tags should still exists)

2022-04-04 15:16 UTC, felicianotech commented on variants/node.Dockerfile.template
> +FROM cimg/%%PARENT%%:%%PARENT_SLUG%%-%%PARENT_TAG%%
This will cause shared variants to fail for images without parentTages enabled.

2022-04-04 15:48 UTC, felicianotech commented on gen-dockerfiles.sh
> -# %%MAIN_SHA%% - deprecated, please use %%PARAM1%%
no deprecation deletions here

2022-04-04 15:59 UTC, felicianotech commented on variants/browsers.Dockerfile.template
> +FROM cimg/%%PARENT%%:%%PARENT_SLUG%%-%%PARENT_TAG%%-node
Here's a possible plan...?

We need to check for two scenarios.... 1) are we in the context of a variant (as opposed to a main/sibling image) and 2) is the parentTags feature enabled?

If 1) is true and 2) is not true, then `%%PARENT_TAG%%` get's replaced by the same value of `%%VERSION_FULL%%`.

If 1) and 2) is true, then `%%PARENT_TAG%%` get's replaced by `$parentSlug-%%VERSION_FULL%%`.

2022-04-18 21:10 UTC, felicianotech requested changes
We're so close.

I did all three test images. Go, Elixir, and Clojure. Go was great. For the other two, only once piece is messed up, the build images file.
<img width="1256" alt="Screen Shot 2022-04-18 at 16 52 35" src="https://user-images.githubusercontent.com/6017470/163878546-7ebdd676-46bf-4084-87fc-94bf81fe9495.png">

I see a double slash problem and a duplicate browsers mention.

We can Zoom in a bit if you'd like.

2022-04-19 21:36 UTC, felicianotech approved these changes
This is ready to be merged! Wooo.

I didn't notice any errors. I tested all three scenarios:

1. an image with parentTags turned off
2. an image with parentTags in FROM
3. an image with parentTags in body

All are working. I did notice one issue though, `defaultParentTag` functionality is missing. This should add some extra lines to the push script to make a simpler/smaller tag for the image that would be considered default. Let's get that done but in a different PR, so we can FINALLY get this one merged.

😄

2022-04-19 22:24 UTC, merged