feat: adds version checking functions
CircleCI-Public/cimg-shared pull request #80
Opened 2023-02-16 19:34 UTC by JalexChen

2023-02-17 14:44 UTC, felicianotech requested changes

2023-02-17 14:44 UTC, felicianotech commented on automated-updates.sh
> +  if [ "$1" = "$2" ]; then
Aren't we defining human readable variable names in the lines above? Shouldn't we then use those variable names?

2023-02-17 14:44 UTC, felicianotech commented on automated-updates.sh
> +#!/bin/bash
This isn't portable.

2023-02-17 14:44 UTC, felicianotech commented on automated-updates.sh
> +vereq() {
More describing function makes. The comments above are very helpful but we can add context into the function name itself by being more descriptive with it.

2023-02-17 16:17 UTC, JalexChen commented
just as a note, since this all rolls up, it doesn't make much sense to make a PR for each function. after talking through in standups, this will be a large PR separated by commits

2023-02-23 17:05 UTC, felicianotech commented on automated-updates.sh
> +getElixirVersion() {
This doesn't fit with the architecture of the cimg build system. Image specific code should live with the image, not `cimg-shared`.

2023-02-23 17:24 UTC, JalexChen commented on automated-updates.sh
> +getElixirVersion() {
yea no problem. i'll take out one of the comments i made and generalize this so each image can call the function(s) to operate

2023-03-02 09:27 UTC, BytesGuy requested changes
@JalexChen a few comments so far 🙂 I might have some more but will review the rest later!

2023-03-02 09:27 UTC, BytesGuy commented on automated-updates.sh
> +shopt -s extglob
Is this still required if we do not have image-specific logic in this file?

2023-03-02 09:27 UTC, BytesGuy commented on automated-updates.sh
> +  # the next three functions work as the version string parsers and are what decides which versions go into the vers array
I would suggest moving these comments above each function for clarity 👍

2023-03-02 09:27 UTC, BytesGuy commented on automated-updates.sh
> +  local cut=$2
Would you be able to comment on how/why these parameters are used? At the moment it seems like this could be dropped down to just the one parameter as line 60 just swaps in `cut` as the new version if it is passed

2023-03-02 14:36 UTC, JalexChen commented on automated-updates.sh
> +shopt -s extglob
yes this can be removed

2023-03-02 15:10 UTC, JalexChen commented on automated-updates.sh
> +  # the next three functions work as the version string parsers and are what decides which versions go into the vers array
done

2023-03-02 15:21 UTC, JalexChen commented on automated-updates.sh
> +  local cut=$2
hmm... you're right. i don't think both parameters are needed. my initial thought was to have a separate parameter to isolate the version, but since we're in a loop and the function is operating on one variable at a time, i wouldn't need to pass in the dirty version.

2023-03-08 10:43 UTC, BytesGuy approved these changes
@JalexChen These functions are looking good! I will approve this but would like to ask if we can have some comments above the functions that are not documented, just so we know what the purpose is, what parameters they accept and what they return. This will make things easier for future modifications

2023-03-08 20:03 UTC, JalexChen commented
@felicianotech - can i get a review on the changes you've requested?

2023-04-19 16:41 UTC, JalexChen commented
closing for now as this technically does not need to be merged at the moment

2023-04-19 16:41 UTC, closed without merging